### ISSUE TITLE
Unable to download a whole directory

### ISSUE THREAD

**Issue by nihithreddy** [mahmoud-eskandari/vuemastery-dl#11]

**Comment by mahmoud-eskandari** [comment]
Please explain your problem,
an example:
`cd ./data/next-level-vue && node ../../mirror.js`

**Comment by nihithreddy** [comment]
For every course there is data.txt file which contains all the links . when i copy the link from the data.txt file and open in the browser then i was able to see the video in the browser but iam unable to download the single video file using node download.js (videourl) command and also iam getting the video not found error more often

**Comment by Araw830** [comment]
https://en.savefrom.net/11-how-to-download-vimeo-video.html
Use this Link to download course video.....

**Comment by nihithreddy** [comment]
Ok will try now
