### ISSUE TITLE
Add new courses

### ISSUE THREAD

**Issue by ajtruex** [mahmoud-eskandari/vuemastery-dl#14]
A couple of new courses have been added to the catalog. If anyone still has access to the links it would be greatly appreciated if they were added to the data folder. The courses are linked below:

[From Vue 2 to Vue 3](https://www.vuemastery.com/courses/from-vue2-to-vue3/from-vue-2-to-vue-3)

[Build a Gmail Clone with Vue 3](https://www.vuemastery.com/courses/build-a-gmail-clone-with-vue3/tour-the-project)

@Elaniobro @mage1k99

**Comment by Fachher** [comment]
Vue2 to Vue 3

https://player.vimeo.com/video/258707456?autoplay=1&app_id=122963
https://player.vimeo.com/video/424215562?autoplay=1&app_id=122963
https://player.vimeo.com/video/425339512?autoplay=1&app_id=122963
https://player.vimeo.com/video/427585737?autoplay=1&app_id=122963
https://player.vimeo.com/video/433041737?autoplay=1&app_id=122963

**Comment by Fachher** [comment]
Build a Gmail Clone with Vue 3

https://player.vimeo.com/video/418119086?autoplay=1&app_id=122963
https://player.vimeo.com/video/417686205?autoplay=1&app_id=122963
https://player.vimeo.com/video/418119086?autoplay=1&app_id=122963
https://player.vimeo.com/video/424719912?autoplay=1&app_id=122963
https://player.vimeo.com/video/432334269?autoplay=1&app_id=122963
https://player.vimeo.com/video/432334539?autoplay=1&app_id=122963
https://player.vimeo.com/video/432334746?autoplay=1&app_id=122963
https://player.vimeo.com/video/435917211?autoplay=1&app_id=122963
https://player.vimeo.com/video/435925588?autoplay=1&app_id=122963
https://player.vimeo.com/video/439008950?autoplay=1&app_id=122963

**Comment by Fachher** [comment]
Both courses are not finished yet

**Comment by mahmoud-eskandari** [comment]
Thanks

**Comment by b805rohit** [comment]
please add component design patterns

**Comment by ajtruex** [comment]
Thank you @Fachher. You're a saint 🙏

**Comment by lohithn4** [comment]
> Both courses are not finished yet

Thank YSM, please update the links as the courses are complete now.

**Comment by Nisgrak** [comment]
#48 resolves this @mahmoud-eskandari

**Comment by aroguecoder** [comment]
It's currently free why not just include the entire catalogue?

**Comment by ThereYouGo-FullList** [comment]
Throwaway account! Copy this, before it gets flagged.

intro-to-vue-js

https://player.vimeo.com/video/258707456?autoplay=1&app_id=122963
https://player.vimeo.com/video/258874670?autoplay=1&app_id=122963
https://player.vimeo.com/video/300867455?autoplay=1&app_id=122963
https://player.vimeo.com/video/258889657?autoplay=1&app_id=122963
https://player.vimeo.com/video/259211539?autoplay=1&app_id=122963
https://player.vimeo.com/video/259233921?autoplay=1&app_id=122963
https://player.vimeo.com/video/259937361?autoplay=1&app_id=122963
https://player.vimeo.com/video/263051367?autoplay=1&app_id=122963
https://player.vimeo.com/video/263911367?autoplay=1&app_id=122963
https://player.vimeo.com/video/264692706?autoplay=1&app_id=122963
https://player.vimeo.com/video/267299472?autoplay=1&app_id=122963

advanced-components

https://player.vimeo.com/video/263589430?autoplay=1&app_id=122963
https://player.vimeo.com/video/264113772?autoplay=1&app_id=122963
https://player.vimeo.com/video/276288371?autoplay=1&app_id=122963
https://player.vimeo.com/video/264184004?autoplay=1&app_id=122963
https://player.vimeo.com/video/276302877?autoplay=1&app_id=122963
https://player.vimeo.com/video/265079382?autoplay=1&app_id=122963
https://player.vimeo.com/video/277359426?autoplay=1&app_id=122963
https://player.vimeo.com/video/265359995?autoplay=1&app_id=122963
https://player.vimeo.com/video/277362944?autoplay=1&app_id=122963
https://player.vimeo.com/video/266460791?autoplay=1&app_id=122963
https://player.vimeo.com/video/277714650?autoplay=1&app_id=122963
https://player.vimeo.com/video/272766967?autoplay=1&app_id=122963

real-world-vue-js

https://player.vimeo.com/video/297369661?autoplay=1&app_id=122963
https://player.vimeo.com/video/277360353?autoplay=1&app_id=122963
https://player.vimeo.com/video/279903602?autoplay=1&app_id=122963
https://player.vimeo.com/video/297766252?autoplay=1&app_id=122963
https://player.vimeo.com/video/282973369?autoplay=1&app_id=122963
https://player.vimeo.com/video/284521373?autoplay=1&app_id=122963
https://player.vimeo.com/video/285671440?autoplay=1&app_id=122963
https://player.vimeo.com/video/286707518?autoplay=1&app_id=122963
https://player.vimeo.com/video/297804361?autoplay=1&app_id=122963

scaling-vue-with-nuxt-js

https://player.vimeo.com/video/311756540?autoplay=1&app_id=122963
https://player.vimeo.com/video/314572866?autoplay=1&app_id=122963
https://player.vimeo.com/video/316653566?autoplay=1&app_id=122963
https://player.vimeo.com/video/317105776?autoplay=1&app_id=122963
https://player.vimeo.com/video/320633290?autoplay=1&app_id=122963
https://player.vimeo.com/video/324333004?autoplay=1&app_id=122963
https://player.vimeo.com/video/325496815?autoplay=1&app_id=122963
https://player.vimeo.com/video/333888973?autoplay=1&app_id=122963
https://player.vimeo.com/video/337883799?autoplay=1&app_id=122963
https://player.vimeo.com/video/343242377?autoplay=1&app_id=122963

mastering-vuex

https://player.vimeo.com/video/297516469?autoplay=1&app_id=122963
https://player.vimeo.com/video/299290718?autoplay=1&app_id=122963
https://player.vimeo.com/video/296998483?autoplay=1&app_id=122963
https://player.vimeo.com/video/297183312?autoplay=1&app_id=122963
https://player.vimeo.com/video/297215375?autoplay=1&app_id=122963
https://player.vimeo.com/video/294957628?autoplay=1&app_id=122963
https://player.vimeo.com/video/296095457?autoplay=1&app_id=122963

next-level-vue

https://player.vimeo.com/video/299718108?autoplay=1&app_id=122963
https://player.vimeo.com/video/297619886?autoplay=1&app_id=122963
https://player.vimeo.com/video/298208305?autoplay=1&app_id=122963
https://player.vimeo.com/video/299962821?autoplay=1&app_id=122963
https://player.vimeo.com/video/300838968?autoplay=1&app_id=122963
https://player.vimeo.com/video/302513491?autoplay=1&app_id=122963
https://player.vimeo.com/video/304941787?autoplay=1&app_id=122963
https://player.vimeo.com/video/306582689?autoplay=1&app_id=122963
https://player.vimeo.com/video/307592723?autoplay=1&app_id=122963
https://player.vimeo.com/video/308504709?autoplay=1&app_id=122963
https://player.vimeo.com/video/311076056?autoplay=1&app_id=122963
https://player.vimeo.com/video/312320460?autoplay=1&app_id=122963
https://player.vimeo.com/video/315508073?autoplay=1&app_id=122963

token-based-authentication

https://player.vimeo.com/video/322541550?autoplay=1&app_id=122963
https://player.vimeo.com/video/327559707?autoplay=1&app_id=122963
https://player.vimeo.com/video/328952884?autoplay=1&app_id=122963
https://player.vimeo.com/video/331308258?autoplay=1&app_id=122963
https://player.vimeo.com/video/336662859?autoplay=1&app_id=122963
https://player.vimeo.com/video/340259889?autoplay=1&app_id=122963
https://player.vimeo.com/video/345127910?autoplay=1&app_id=122963

watch-us-build-trello-clone

https://player.vimeo.com/video/327844370?autoplay=1&app_id=122963
https://player.vimeo.com/video/329214344?autoplay=1&app_id=122963
https://player.vimeo.com/video/331459804?autoplay=1&app_id=122963
https://player.vimeo.com/video/332476395?autoplay=1&app_id=122963
https://player.vimeo.com/video/332695521?autoplay=1&app_id=122963
https://player.vimeo.com/video/334001031?autoplay=1&app_id=122963
https://player.vimeo.com/video/335300449?autoplay=1&app_id=122963
https://player.vimeo.com/video/335301632?autoplay=1&app_id=122963
https://player.vimeo.com/video/336403919?autoplay=1&app_id=122963
https://player.vimeo.com/video/336411746?autoplay=1&app_id=122963

beautify-with-vuetify

https://player.vimeo.com/video/346032810?autoplay=1&app_id=122963
https://player.vimeo.com/video/350501837?autoplay=1&app_id=122963
https://player.vimeo.com/video/353308521?autoplay=1&app_id=122963
https://player.vimeo.com/video/357089986?autoplay=1&app_id=122963
https://player.vimeo.com/video/359661975?autoplay=1&app_id=122963
https://player.vimeo.com/video/362841967?autoplay=1&app_id=122963
https://player.vimeo.com/video/368669029?autoplay=1&app_id=122963
https://player.vimeo.com/video/378430249?autoplay=1&app_id=122963
https://player.vimeo.com/video/380861996?autoplay=1&app_id=122963

animating-vue

https://player.vimeo.com/video/351308397?autoplay=1&app_id=122963
https://player.vimeo.com/video/353909159?autoplay=1&app_id=122963
https://player.vimeo.com/video/358710484?autoplay=1&app_id=122963
https://player.vimeo.com/video/361550074?autoplay=1&app_id=122963
https://player.vimeo.com/video/367390374?autoplay=1&app_id=122963
https://player.vimeo.com/video/372000380?autoplay=1&app_id=122963
https://player.vimeo.com/video/375052563?autoplay=1&app_id=122963
https://player.vimeo.com/video/379804181?autoplay=1&app_id=122963
https://player.vimeo.com/video/380155578?autoplay=1&app_id=122963

vue-3-essentials

https://player.vimeo.com/video/364111799?autoplay=1&app_id=122963
https://player.vimeo.com/video/364140610?autoplay=1&app_id=122963
https://player.vimeo.com/video/365085315?autoplay=1&app_id=122963
https://player.vimeo.com/video/365099441?autoplay=1&app_id=122963
https://player.vimeo.com/video/365160899?autoplay=1&app_id=122963
https://player.vimeo.com/video/365352006?autoplay=1&app_id=122963
https://player.vimeo.com/video/372753110?autoplay=1&app_id=122963
https://player.vimeo.com/video/372755942?autoplay=1&app_id=122963
https://player.vimeo.com/video/375785689?autoplay=1&app_id=122963
https://player.vimeo.com/video/420508038?autoplay=1&app_id=122963
https://player.vimeo.com/video/424955491?autoplay=1&app_id=122963

unit-testing

https://player.vimeo.com/video/385713441?autoplay=1&app_id=122963
https://player.vimeo.com/video/387189765?autoplay=1&app_id=122963
https://player.vimeo.com/video/391719920?autoplay=1&app_id=122963
https://player.vimeo.com/video/398001031?autoplay=1&app_id=122963
https://player.vimeo.com/video/404668293?autoplay=1&app_id=122963
https://player.vimeo.com/video/414881728?autoplay=1&app_id=122963

vue-3-reactivity

https://player.vimeo.com/video/388752844?autoplay=1&app_id=122963
https://player.vimeo.com/video/388759486?autoplay=1&app_id=122963
https://player.vimeo.com/video/392347730?autoplay=1&app_id=122963
https://player.vimeo.com/video/400699168?autoplay=1&app_id=122963
https://player.vimeo.com/video/397194972?autoplay=1&app_id=122963
https://player.vimeo.com/video/397197076?autoplay=1&app_id=122963

component-design-Patterns

https://player.vimeo.com/video/394725602?autoplay=1&app_id=122963
https://player.vimeo.com/video/394498766?autoplay=1&app_id=122963
https://player.vimeo.com/video/399734836?autoplay=1&app_id=122963
https://player.vimeo.com/video/409867593?autoplay=1&app_id=122963
https://player.vimeo.com/video/424213580?autoplay=1&app_id=122963
https://player.vimeo.com/video/431605455?autoplay=1&app_id=122963
https://player.vimeo.com/video/437260447?autoplay=1&app_id=122963
https://player.vimeo.com/video/441489357?autoplay=1&app_id=122963
https://player.vimeo.com/video/448610522?autoplay=1&app_id=122963

build-a-gmail-clone-with-vue3

https://player.vimeo.com/video/417686205?autoplay=1&app_id=122963
https://player.vimeo.com/video/418119086?autoplay=1&app_id=122963
https://player.vimeo.com/video/424719912?autoplay=1&app_id=122963
https://player.vimeo.com/video/432334269?autoplay=1&app_id=122963
https://player.vimeo.com/video/432334539?autoplay=1&app_id=122963
https://player.vimeo.com/video/432334746?autoplay=1&app_id=122963
https://player.vimeo.com/video/435917211?autoplay=1&app_id=122963
https://player.vimeo.com/video/435925588?autoplay=1&app_id=122963
https://player.vimeo.com/video/439008950?autoplay=1&app_id=122963
https://player.vimeo.com/video/439009520?autoplay=1&app_id=122963
https://player.vimeo.com/video/441251067?autoplay=1&app_id=122963
https://player.vimeo.com/video/441252800?autoplay=1&app_id=122963
https://player.vimeo.com/video/449574598?autoplay=1&app_id=122963
https://player.vimeo.com/video/449582938?autoplay=1&app_id=122963
https://player.vimeo.com/video/450616466?autoplay=1&app_id=122963
https://player.vimeo.com/video/455342339?autoplay=1&app_id=122963

vue3-forms

https://player.vimeo.com/video/457363869?autoplay=1&app_id=122963
https://player.vimeo.com/video/458419816?autoplay=1&app_id=122963
https://player.vimeo.com/video/459058559?autoplay=1&app_id=122963
https://player.vimeo.com/video/467985438?autoplay=1&app_id=122963
https://player.vimeo.com/video/478759502?autoplay=1&app_id=122963
https://player.vimeo.com/video/480558076?autoplay=1&app_id=122963
https://player.vimeo.com/video/493121878?autoplay=1&app_id=122963
https://player.vimeo.com/video/505012138?autoplay=1&app_id=122963
https://player.vimeo.com/video/517344724?autoplay=1&app_id=122963

vue3-deep-dive-with-evan-you

https://player.vimeo.com/video/413320671?autoplay=1&app_id=122963
https://player.vimeo.com/video/413172106?autoplay=1&app_id=122963
https://player.vimeo.com/video/410406205?autoplay=1&app_id=122963
https://player.vimeo.com/video/410199064?autoplay=1&app_id=122963
https://player.vimeo.com/video/410256224?autoplay=1&app_id=122963
https://player.vimeo.com/video/410291443?autoplay=1&app_id=122963
https://player.vimeo.com/video/410676185?autoplay=1&app_id=122963
https://player.vimeo.com/video/410680764?autoplay=1&app_id=122963
https://player.vimeo.com/video/410687425?autoplay=1&app_id=122963
https://player.vimeo.com/video/410711530?autoplay=1&app_id=122963
https://player.vimeo.com/video/410715243?autoplay=1&app_id=122963
https://player.vimeo.com/video/410722048?autoplay=1&app_id=122963
https://player.vimeo.com/video/411046002?autoplay=1&app_id=122963
https://player.vimeo.com/video/411053073?autoplay=1&app_id=122963
https://player.vimeo.com/video/411057133?autoplay=1&app_id=122963

intro-to-vue-3

https://player.vimeo.com/video/429439600?autoplay=1&app_id=122963
https://player.vimeo.com/video/430513164?autoplay=1&app_id=122963
https://player.vimeo.com/video/430892048?autoplay=1&app_id=122963
https://player.vimeo.com/video/432257268?autoplay=1&app_id=122963
https://player.vimeo.com/video/436245555?autoplay=1&app_id=122963
https://player.vimeo.com/video/436573740?autoplay=1&app_id=122963
https://player.vimeo.com/video/437484985?autoplay=1&app_id=122963
https://player.vimeo.com/video/440157813?autoplay=1&app_id=122963
https://player.vimeo.com/video/440514041?autoplay=1&app_id=122963
https://player.vimeo.com/video/441165140?autoplay=1&app_id=122963
https://player.vimeo.com/video/442485891?autoplay=1&app_id=122963

from-vue2-to-vue3

https://player.vimeo.com/video/424215562?autoplay=1&app_id=122963
https://player.vimeo.com/video/425339512?autoplay=1&app_id=122963
https://player.vimeo.com/video/427585737?autoplay=1&app_id=122963
https://player.vimeo.com/video/433041737?autoplay=1&app_id=122963
https://player.vimeo.com/video/438959871?autoplay=1&app_id=122963
https://player.vimeo.com/video/442885410?autoplay=1&app_id=122963

real-world-vue3

https://player.vimeo.com/video/462853296?autoplay=1&app_id=122963
https://player.vimeo.com/video/462876299?autoplay=1&app_id=122963
https://player.vimeo.com/video/470251780?autoplay=1&app_id=122963
https://player.vimeo.com/video/472810738?autoplay=1&app_id=122963
https://player.vimeo.com/video/477765119?autoplay=1&app_id=122963
https://player.vimeo.com/video/488382833?autoplay=1&app_id=122963
https://player.vimeo.com/video/490917120?autoplay=1&app_id=122963
https://player.vimeo.com/video/494544547?autoplay=1&app_id=122963

vue3-typescript

https://player.vimeo.com/video/467481375?autoplay=1&app_id=122963
https://player.vimeo.com/video/473662632?autoplay=1&app_id=122963
https://player.vimeo.com/video/473998588?autoplay=1&app_id=122963
https://player.vimeo.com/video/486226307?autoplay=1&app_id=122963
https://player.vimeo.com/video/492858617?autoplay=1&app_id=122963
https://player.vimeo.com/video/501230219?autoplay=1&app_id=122963
https://player.vimeo.com/video/505794251?autoplay=1&app_id=122963
https://player.vimeo.com/video/510916818?autoplay=1&app_id=122963
https://player.vimeo.com/video/516377523?autoplay=1&app_id=122963
https://player.vimeo.com/video/519596515?autoplay=1&app_id=122963

touring-vue-router

https://player.vimeo.com/video/471197070?autoplay=1&app_id=122963
https://player.vimeo.com/video/471553156?autoplay=1&app_id=122963
https://player.vimeo.com/video/475248686?autoplay=1&app_id=122963
https://player.vimeo.com/video/482846883?autoplay=1&app_id=122963
https://player.vimeo.com/video/489490162?autoplay=1&app_id=122963
https://player.vimeo.com/video/498189741?autoplay=1&app_id=122963
https://player.vimeo.com/video/503618233?autoplay=1&app_id=122963
https://player.vimeo.com/video/510430996?autoplay=1&app_id=122963
https://player.vimeo.com/video/522434741?autoplay=1&app_id=122963

real-world-testing

https://player.vimeo.com/video/530491857?autoplay=1&app_id=122963

vuex-fundamentals

https://player.vimeo.com/video/515894346?autoplay=1&app_id=122963
https://player.vimeo.com/video/529759116?autoplay=1&app_id=122963

unit-testing-vue-3

https://player.vimeo.com/video/510489703?autoplay=1&app_id=122963
https://player.vimeo.com/video/514104358?autoplay=1&app_id=122963
https://player.vimeo.com/video/514106269?autoplay=1&app_id=122963
https://player.vimeo.com/video/514344677?autoplay=1&app_id=122963
https://player.vimeo.com/video/518376232?autoplay=1&app_id=122963
https://player.vimeo.com/video/518384316?autoplay=1&app_id=122963
