### ISSUE TITLE
Course Data Update

### ISSUE THREAD

**Issue by wduandy** [mahmoud-eskandari/vuemastery-dl#15]
Hello! I'm new at GitHub and i don't know how to contribute to the repo. I have access to the site and i've made a pull request with the data of:

from-vue-2-to-vue-3
build-a-gmail-clone-with-vue3

How to push?

**Comment by mahmoud-eskandari** [comment]
Hey

Run `document.getElementsByTagName('iframe')[0].src` in the browser console(F12 -> console) to get {Video LINK}
(Refresh the page for each parts)
copy each link and paste into 
```/data/from-vue-2-to-vue-3/data.txt```
...
Check one of the existing folders as an example

go to [data](https://github.com/mahmoud-eskandari/vuemastery-dl/tree/master/data) and click to (add file button) on top-right corner

Thanks for your attention

**Comment by mahmoud-eskandari** [comment]
I tracked your activity 
[data.txt](https://github.com/wduandy/vuemastery-dl/blob/patch-1/data/from-vue2-to-vue3/data.txt)

click to branche names and create merge request to your master branch then click on master branch and click on (Create Pull request) button
