### ISSUE TITLE
Vue 3 Composition API course

### ISSUE THREAD

**Issue by mehrabsha** [mahmoud-eskandari/vuemastery-dl#23]
[Vue 3 Composition API](https://www.vuemastery.com/courses/vue-3-essentials/setup-and-reactive-references/)

1. https://player.vimeo.com/video/364111799?autoplay=1&app_id=122963
2. https://player.vimeo.com/video/364140610?autoplay=1&app_id=122963
3. https://player.vimeo.com/video/365085315?autoplay=1&app_id=122963
4. https://player.vimeo.com/video/365099441?autoplay=1&app_id=122963
5. https://player.vimeo.com/video/365160899?autoplay=1&app_id=122963
6. https://player.vimeo.com/video/365352006?autoplay=1&app_id=122963
7. https://player.vimeo.com/video/372753110?autoplay=1&app_id=122963
8. https://player.vimeo.com/video/372755942?autoplay=1&app_id=122963
9. https://player.vimeo.com/video/375785689?autoplay=1&app_id=122963
10. https://player.vimeo.com/video/420508038?autoplay=1&app_id=122963
11. https://player.vimeo.com/video/424955491?autoplay=1&app_id=122963

**Comment by mahmoud-eskandari** [comment]
Thanks
