### ISSUE TITLE
Duplicate and extra file

### ISSUE THREAD

**Issue by ankushpersonal** [mahmoud-eskandari/vuemastery-dl#33]
In this folder: ```vue3-deep-dive-with-evan-you/data.txt```. All the files are correct but there is also a similar folder with the name: ```vue-3-deep-dive-with-evan-you```. In this folder in data.txt the line numbers `4 and 5` are the same. Though it is not downloading the same file twice, we may miss the extra video which is present in the first file. Please check that. Thank you for the repo. Its very helpful :smiling_face_with_three_hearts:

**Comment by mahmoud-eskandari** [comment]
Line 4 & 5 aren't same.
Thanks

**Comment by ankushpersonal** [comment]
Please check this file. I have attached the screenshot. 
![8DD8FFED-B020-4A4A-9D89-731AD17D80B7](https://user-images.githubusercontent.com/42799203/100271030-d3c1a480-2f7e-11eb-9ee9-23a49bdba001.png)
