### ISSUE TITLE
please add typescript + vue 3 and vue3 forms

### ISSUE THREAD

**Issue by AshwinTayson** [mahmoud-eskandari/vuemastery-dl#35]
https://www.vuemastery.com/courses/vue3-typescript

https://www.vuemastery.com/courses/vue3-forms

**Comment by carlos-mora** [comment]
May be Touring Vue Router too? https://www.vuemastery.com/courses/touring-vue-router

**Comment by mage1k99** [comment]
Vue3 typescript is added with one lesson left which will be available on march 16.

now vue3 forms is left to be added
