### ISSUE TITLE
free the-vuejs-3-master-class

### ISSUE THREAD

**Issue by MiladRapezani** [mahmoud-eskandari/vuemastery-dl#43]
<div dir="rtl">
سلام و تشکر از شما
دوره the-vuejs-3-master-class از سایت vueschool به مدت کوتاهی (تنها 2 روز) بصورت رایگان هستش. لطفا جلساتش رو در اینجا قرار دهید.

https://vueschool.io/courses/the-vuejs-3-master-class
</div>

**Comment by mahmoud-eskandari** [comment]
این رپازیتوری صرفا برای دانلود از Vuemastery
ساخته شده

و  با ویو اسکول قابل انطباق نیست
