### ISSUE TITLE
Please update unit testing with the missing video

### ISSUE THREAD

**Issue by titiceral** [mahmoud-eskandari/vuemastery-dl#44]
in unit-testing directory the video 6 "Stubbing Child Components" is missing.

**Comment by kruuger** [comment]
can't be done just like that. you need active subscription.
maybe we can raise money (for example 4x5$) for month and update missing links? anyone interesed?

**Comment by LeonardSSH** [comment]
@kruuger Yes, it would be a solution, I'm in! 
@mahmoud-eskandari what do you think about that? ^^

**Comment by kruuger** [comment]
> @kruuger Yes, it would be a solution, I'm in!
> @mahmoud-eskandari what do you think about that? ^^

April 23-25 all will be FREE, so we can complete all of them.

**Comment by LeonardSSH** [comment]
> 
> 
> > @kruuger Yes, it would be a solution, I'm in!
> > @mahmoud-eskandari what do you think about that? ^^
> 
> April 23-25 all will be FREE, so we can complete all of them.

Ah, that's right, I forgot. 🤣😂😂
