### ISSUE TITLE
All courses unlocked April 23-25

### ISSUE THREAD

**Issue by mage1k99** [mahmoud-eskandari/vuemastery-dl#45]
Access the ultimate library of Vue courses during Free Weekend.

And make PR for missing content [Register here](https://www.vuemastery.com/free-weekend)

**Comment by MiladRapezani** [comment]
<div dir="rtl">
خبر خوش: از تاریخ Friday April 23 - Sunday April 25 که میشه: 3، 4، 5 اردیبهشت 1400 همه ی دوره های vuemastery رایگان خواهد بود.
لطفا همه ی دوره ها رو دریافت کنید و ایجاد قرار دهید.
همه مون بهره مند بشیم بالاخره : )
[پیوند برای ثبت نام](https://www.vuemastery.com/free-weekend/?utm_source=newsletter&utm_medium=email&utm_campaign=were_unlocking_our_entire_course_library&utm_term=2021-04-12)
</div>

**Comment by mahmoud-eskandari** [comment]
لطفا خودتان این کار رو تا اونجایی که میتونید انجام بدید

توضیحات نوشته شده

**Comment by mage1k99** [comment]
Yes for sure @mahmoud-eskandari

**Comment by MiladRapezani** [comment]
<div dir="rtl">
من بلد نیستم که چجوری اینجا قرار بدم. راه حلش رو هم توی این مخزن ندیدم. کجا رو بخونم؟
</div>

**Comment by mage1k99** [comment]
## How to contribute

- fork the repo.
- create a folder inside the data folder with the name of the course tittle
- For example the course title "intro to vue js" can be created as "intro-to-vue-js"
- inside the created folder, create a file "data.txt"
- paste the vimeo link for every lessons in the course with every lesson in new line
- Example: If there are 2 lessons then it would be
```
https://player.vimeo.com/video/258707456?autoplay=1&app_id=122963
https://player.vimeo.com/video/258874670?autoplay=1&app_id=122963

```

## How to obtain these vimeo player links ??

Its quite easy. There are two ways to obtain them. you can use extensions like viemo downloader

or

- Go lesson that you want to obtain link.
- press F12 and search for url by pressing ctrl + F
- Type `player.v`

![image](https://user-images.githubusercontent.com/46259860/114542426-8a47cc80-9c75-11eb-9e06-324d59d2f1df.png)

- You would be highlighted the url, copy it
