### ISSUE TITLE
If File (.mp4) contains "/" in it, that requires another directory

### ISSUE THREAD

**Issue by NinjaGamer107** [mahmoud-eskandari/vuemastery-dl#5]
I found this in "Scaling Vue with Nuxt.js" course, that one lesson throws an error becuase it expects another directory. I fixed this by making the directory it wanted, but I suspect that this is not intended behaviour.

This is the Error I get:
`07 - Async/Await from Vue Mastery, Downloading...
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\Aleksa\Documents\GitHub\vuemastery-dl\data\scaling-vue-with-nuxt-js\07 - Async\Await from Vue Mastery.mp4'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:277:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)`

**Comment by mahmoud-eskandari** [comment]
this issue has fixed in latest version

https://github.com/mahmoud-eskandari/vuemastery-dl/blob/a9783db64fbb77a5b6ba31cc75d91ad3bf8f3221/download.js#L22
