### ISSUE TITLE
Idea: could the page itself also be added? in html

### ISSUE THREAD

**Issue by dimitrihilverda** [mahmoud-eskandari/vuemastery-dl#53]
The videolinks are cool, but the html pages itself are also a nice extra's, is it possible to add them also?
Maybe someone could make a script to get all the html pages?

I started downloading the one by one. but that is kind of a pain.

**Comment by LeonardSSH** [comment]
There is an easy way.. you can get the entire div block with:
```js
document.getElementById("lessonContent").innerHTML
```
and then convert into [Markdown](https://www.browserling.com/tools/html-to-markdown).

**Comment by aroguecoder** [comment]
I second this idea.
Mainly because there's no console on android.

**Comment by LeonardSSH** [comment]
https://github.com/mahmoud-eskandari/vuemastery-dl/pull/54
