### ISSUE TITLE
duplicate url in in data/real-world-vue-js/data.txt

### ISSUE THREAD

**Issue by Ekeler** [mahmoud-eskandari/vuemastery-dl#6]
Real World Vue.js - Lesson 7 - Global Components is missing and the url for lesson 8 is duplicated (lines 7 and 8 are identical).

**Comment by mahmoud-eskandari** [comment]
I no longer have access to the vuemastery.com
I hope someone will correct it

**Comment by mahmoud-eskandari** [comment]
It changed now
