### ISSUE TITLE
Video Not found

### ISSUE THREAD

**Issue by muffettsman** [mahmoud-eskandari/vuemastery-dl#7]
when trying to pull from mirror.js or download.js often getting "Video not found" errors.

https://player.vimeo.com/video/350501837?autoplay=1&app_id=122963

`node download.js https://player.vimeo.com/video/350501837?autoplay=1&app_id=122963
[1] 31194
Video not found

[1]+  Done                    node download.js https://player.vimeo.com/video/350501837?autoplay=1`

**Comment by mahmoud-eskandari** [comment]
I haven't access to Vuemastery anymore
We should wait for new PRs

**Comment by Fachher** [comment]
@mahmoud-eskandari Your script does not work for me. Could you please double check if it still work.

**Comment by mahmoud-eskandari** [comment]
It fixed in latest commit
